version: '1'
services:
  pokedex-vue3:
    container_name: pokedex-vue3-client-side
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - ./:/app
      - /app/node_modules 
    environment: 
      - CHOKIDAR_USEPOLLING=true